tabbycat/urls.py
from urllib.parse import urlparse

from django.conf import settings
from django.contrib import admin, messages
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.urls import include, path
from django.utils.translation import gettext as _
from django.views.i18n import JavaScriptCatalog

import tournaments.views
from importer.views import LoadDemoView
from users.views import BlankSiteStartView

admin.autodiscover()

# ==============================================================================
# Base Patterns
# ==============================================================================

urlpatterns = [

    # Indices
    path('',
        tournaments.views.PublicSiteIndexView.as_view(),
        name='tabbycat-index'),
    path('start/',
        BlankSiteStartView.as_view(),
        name='blank-site-start'),
    path('create/',
        tournaments.views.CreateTournamentView.as_view(),
        name='tournament-create'),
    path('load-demo/',
        LoadDemoView.as_view(),
        name='load-demo'),
    path('inactive/',
        tournaments.views.PublicSiteInactiveTournamentsView.as_view(),
        name='tabbycat-inactive-tournaments'),

    # Top Level Pages
    path('style/',
        tournaments.views.StyleGuideView.as_view(),
        name='style-guide'),

    # Set language override
    path('i18n/',
        include('django.conf.urls.i18n')),

    # JS Translations Catalogue; includes all djangojs files in locale folders
    path('jsi18n/',
         JavaScriptCatalog.as_view(domain="djangojs"),
         name='javascript-catalog'),

    # Summernote (WYSYWIG)
    path('summernote/',
        include('django_summernote.urls')),

    # Admin area
    path('jet/',
        include('jet.urls', 'jet')),
    path('database/',
        admin.site.urls),

    # Accounts
    path('accounts/', include('users.urls')),

    # Notifications
    path('notifications/',
        include('notifications.urls')),

    # API
    path('api',
        include('api.urls')),

    # Archive import/export
    path('archive/',
        include('importer.urls_archive')),

    # Tournament URLs
    path('<slug:tournament_slug>/',
        include('tournaments.urls')),
]

if settings.DEBUG and settings.ENABLE_DEBUG_TOOLBAR:  # Only serve debug toolbar when on DEBUG
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))


# ==============================================================================
# Logout/Login Confirmations
# ==============================================================================

# These messages don't always work properly with unit tests, so set fail_silently=True

@receiver(user_logged_in)
def on_user_logged_in(sender, request, **kwargs):
    if not urlparse(request.META.get('HTTP_REFERER')).path == '/accounts/login/':
        # The message is extraneous when their account was just created
        return
    if kwargs.get('user'):
        messages.info(request,
            _("Hi, %(user)s — you just logged in!")  % {'user': kwargs['user'].username},
            fail_silently=True)
    else: # should never happen, but just in case
        messages.info(request, _("Welcome! You just logged in!"), fail_silently=True)

tabbycat/draw/models.py
import logging

from django.contrib.humanize.templatetags.humanize import ordinal
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db import models
from django.utils.translation import gettext, gettext_lazy as _

from tournaments.utils import get_side_name
from utils.fields import ChoiceArrayField

from .generator import DRAW_FLAG_DESCRIPTIONS

logger = logging.getLogger(__name__)


class DebateManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super().get_queryset().select_related('round')


class Debate(models.Model):
    STATUS_NONE = 'N'
    STATUS_POSTPONED = 'P'
    STATUS_DRAFT = 'D'
    STATUS_CONFIRMED = 'C'
    STATUS_CHOICES = (
        (STATUS_NONE, _("none")),
        (STATUS_POSTPONED, _("postponed")),
        (STATUS_DRAFT, _("draft")),
        (STATUS_CONFIRMED, _("confirmed")),
    )
    STATUS_CHOICES_RESTRICTED = (  # If postponements are disabled - used in forms
        (STATUS_NONE, _("none")),
        (STATUS_DRAFT, _("draft")),
        (STATUS_CONFIRMED, _("confirmed")),
    )

    objects = DebateManager()

    round = models.ForeignKey('tournaments.Round', models.CASCADE, db_index=True,
        verbose_name=_("round"))
    venue = models.ForeignKey('venues.Venue', models.SET_NULL, blank=True, null=True,
        verbose_name=_("room"))

    bracket = models.FloatField(default=0,
        verbose_name=_("bracket"))
    room_rank = models.IntegerField(default=0,
        verbose_name=_("room rank"))

    flags = ChoiceArrayField(blank=True, default=list,
        base_field=models.CharField(max_length=15, choices=DRAW_FLAG_DESCRIPTIONS))

    importance = models.IntegerField(default=0, choices=[(i, i) for i in range(-2, 3)],
        verbose_name=_("importance"))
    result_status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_NONE,
        verbose_name=_("result status"))
    sides_confirmed = models.BooleanField(default=True,
        verbose_name=_("sides confirmed"),
        help_text=_("If unchecked, the sides assigned to teams in this debate are just placeholders."))

    class Meta:
        verbose_name = _("debate")
        verbose_name_plural = _("debates")

    def __str__(self):
        description = "[{}/{}/{}] ".format(self.round.tournament.slug, self.round.abbreviation, self.id)
        try:
            description += self.matchup
        except Exception:
            logger.exception("Error rendering Debate.matchup in Debate.__str__")
            description += "<error showing teams>"
        return description

    @property
    def matchup(self):
        # This method is used by __str__, so it's not allowed to crash (ever)
        if not self.sides_confirmed:
            teams_list = ", ".join([dt.team.short_name for dt in self.debateteam_set.all()])
            # Translators: This is appended to a list of teams, e.g. "Auckland
            # 1, Vic Wellington 1 (sides not confirmed)". Mind the leading
            # space.
            return teams_list + gettext(" (sides not confirmed)")

        try:
            # This can sometimes arise during the call to self.round.tournament.sides
            # if preferences aren't loaded correctly, which happens in `manage.py shell`.
            sides = self.round.tournament.sides
        except IndexError:
            return self._teams_and_sides_display()  # fallback

        try:
            # Translators: This goes between teams in a debate, e.g. "Auckland 1
            # vs Vic Wellington 1". Mind the leading and trailing spaces.
            return gettext(" vs ").join(self.get_team(side).short_name for side in sides)
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            return self._teams_and_sides_display()

    def _teams_and_sides_display(self):
        return ", ".join(["%s (%s)" % (dt.team.short_name, dt.get_side_display())
                for dt in self.debateteam_set.all()])

    @property
    def matchup_codes(self):
        # Like matchup, but uses team codes. It is not as protected.
        if not self.sides_confirmed:
            teams_list = ", ".join([dt.team.code_name for dt in self.debateteam_set.all()])
            return teams_list + gettext(" (sides not confirmed)")

        try:
            sides = self.round.tournament.sides
            return gettext(" vs ").join(self.get_team(side).code_name for side in sides)
        except (IndexError, ObjectDoesNotExist, MultipleObjectsReturned):
            return ", ".join(["%s (%s)" % (dt.team.code_name, dt.get_side_display())
                for dt in self.debateteam_set.all()])

    # --------------------------------------------------------------------------
    # Team properties
    # --------------------------------------------------------------------------
    # Team properties are stored in the dict `self._team_properties`, except for
    # the list of all teams, which is in `self._teams`. These are lazily
    # evaluated: on the first call of any team property,
    # `self._populate_teams()` is run to populate all team properties in a
    # single database query, then the appropriate value is returned.
    #
    # If the team in question doesn't exist or there is more than one, the
    # property in question will raise an ObjectDoesNotExist or
    # MultipleObjectsReturned exception, so that it behaves like a database
    # query. This exception raising is lazy: it does so only when the errant
    # property is called, rather than raising straight away in
    # `self._populate_teams()`.
    #
    # Callers that wish to retrieve the teams of many debates should add
    #   prefetch_related(Prefetch('debateteam_set',
    #       queryset=DebateTeam.objects.select_related('team'))
    # to their query set.

    def _populate_teams(self):
        """Populates the team attributes from self.debateteam_set."""
        dts = self.debateteam_set.all()
        if not dts._prefetch_done:  # uses internal undocumented flag of Django's QuerySet class
            dts = dts.select_related('team')

        self._teams = []
        self._multiple_found = []
        self._team_properties = {}

        for dt in dts:
            self._teams.append(dt.team)
            team_key = '%s_team' % dt.side
            dt_key = '%s_dt' % dt.side
            if team_key in self._team_properties:
                self._multiple_found.extend([team_key, dt_key])
            self._team_properties[team_key] = dt.team
            self._team_properties[dt_key] = dt

    def _team_property(attr):  # noqa: N805
        """Used to construct properties that rely on self._populate_teams()."""
        @property
        def _property(self):
            if not hasattr(self, '_team_properties'):
                self._populate_teams()
            if attr in self._multiple_found:
                raise MultipleDebateTeamsError("Multiple debate teams found for '%s' in debate ID %d. "
                    "Teams in debate are: %s." % (attr, self.id, self._teams_and_sides_display()))
            try:
                return self._team_properties[attr]
            except KeyError:
                raise NoDebateTeamFoundError("No debate team found for '%s' in debate ID %d. "
                    "Teams in debate are: %s." % (attr, self.id, self._teams_and_sides_display()))
        return _property

    @property
    def teams(self):
        # No need for _team_property overhead, this list is guaranteed to exist
        # (it just might be empty).
        if not hasattr(self, '_teams'):
            self._populate_teams()
        return self._teams

    def debateteams_ordered(self):
        for side in self.round.tournament.sides:
            yield self.get_dt(side)

    aff_team = _team_property('aff_team')
    neg_team = _team_property('neg_team')
    og_team = _team_property('og_team')
    oo_team = _team_property('oo_team')
    cg_team = _team_property('cg_team')
    co_team = _team_property('co_team')
    aff_dt = _team_property('aff_dt')
    neg_dt = _team_property('neg_dt')
    og_dt = _team_property('og_dt')
    oo_dt = _team_property('oo_dt')
    cg_dt = _team_property('cg_dt')
    co_dt = _team_property('co_dt')

    def get_team(self, side):
        return getattr(self, '%s_team' % side)

    def get_dt(self, side):
        """dt = DebateTeam"""
        return getattr(self, '%s_dt' % side)

    # --------------------------------------------------------------------------
    # Other properties
    # --------------------------------------------------------------------------

    @property
    def confirmed_ballot(self):
        """Returns the confirmed BallotSubmission for this debate, or None if
        there is no such ballot submission."""
        try:
            return self._confirmed_ballot
        except AttributeError:
            try:
                self._confirmed_ballot = self.ballotsubmission_set.get(confirmed=True)
            except ObjectDoesNotExist:
                self._confirmed_ballot = None
            return self._confirmed_ballot

    @property
    def history(self):
        try:
            return self._history
        except AttributeError:
            self._history = self.aff_team.seen(self.neg_team, before_round=self.round.seq)
            return self._history

    @property
    def related_adjudicator_set(self):
        """Used by objects that work with both Debate and PreformedPanel."""
        return self.debateadjudicator_set

    @property
    def adjudicators(self):
        """Returns an AdjudicatorAllocation containing the adjudicators for this
        debate."""
        try:
            return self._adjudicators
        except AttributeError:
            from adjallocation.allocation import AdjudicatorAllocation
            self._adjudicators = AdjudicatorAllocation(self, from_db=True)
            return self._adjudicators


class DebateTeamManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):

tabbycat/draw/templates/draw_alerts_adjudicators.html
{% load humanize static debate_tags i18n %}

{% with no_chair=round.num_debates_without_chair even_panel=round.num_debates_with_even_panel duplicates=round.duplicate_panellists unavailable_allocated=round.unavailable_adjudicators_allocated unallocated=round.num_available_adjudicators_not_allocated %}

  {% if no_chair > 0 %}
    {% blocktrans trimmed asvar text count ndebates=no_chair %}
      1 debate does not have a chair.
    {% plural %}
      {{ ndebates }} debates do not have a chair.
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="danger" %}
  {% endif %}

  {% if duplicates %}
    {% blocktrans trimmed asvar text with adjudicators=duplicates|join:", " count nadjs=duplicates|length %}
      <strong>{{ adjudicators }}</strong> is adjudicating multiple debates.
    {% plural %}
      The following <strong>{{ nadjs }}</strong> adjudicators are adjudicating multiple debates: <strong>{{ adjudicators }}</strong>
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="danger" %}
  {% endif %}

  {% if round.ballots_per_debate == 'per-adj' and even_panel > 0 %}
    {% blocktrans trimmed asvar text count ndebates=even_panel %}
      1 debate has a panel with an even number of adjudicators.
    {% plural %}
      {{ ndebates }} debates have panels with an even number of adjudicators.
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="warning" %}
  {% endif %}

  {% if debates_with_adj_conflicts > 0 %}
    {% blocktrans trimmed asvar text count ndebates=debates_with_adj_conflicts %}
      1 debate has an adjudicator conflict.
    {% plural %}
      {{ ndebates }} debates have adjudicator conflicts.
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="warning" %}
  {% endif %}

  {% if unavailable_allocated %}
    {% blocktrans trimmed asvar text with adjudicators=unavailable_allocated|join:", " count nadjs=unavailable_allocated|length %}
      <strong>{{ adjudicators }}</strong> is unavailable this round, but is assigned to a debate.
    {% plural %}
      The following <strong>{{ nadjs }}</strong> adjudicators are unavailable this round, but are assigned to debates: <strong>{{ adjudicators }}</strong>
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="danger" %}
  {% endif %}

  {% if unallocated > 0 %}
    {% blocktrans trimmed asvar text count ndebates=unallocated %}
      1 adjudicator is available but not assigned to a debate.
    {% plural %}
      {{ ndebates }} adjudicators are available but not assigned to a debate.
    {% endblocktrans %}
    {% include "components/item-info.html" with nopad=True type="warning" %}
  {% endif %}

{% endwith %}

tabbycat/draw/templates/draw_base.html
{% extends "tables/base_vue_table.html" %}
{% load debate_tags i18n %}

{% block page-subnav-sections %}
  <a class="btn btn-outline-primary " href="{% roundurl 'availability-index' %}">
    <i data-feather="chevron-left"></i> {% trans "Availability" %}
  </a>

  <div class="btn-group flex-wrap" role="group">
    <a href="{% roundurl 'edit-debate-teams' round %}" class="btn btn-outline-primary">
      {% trans "Edit Sides/Matchups" %}
    </a>
  </div>
  <div class="btn-group flex-wrap" role="group">
    <a href="{% roundurl 'draw-confirm-regenerate' %}" class="btn btn-outline-primary">
      {% trans "Redo Draw" %}
    </a>
    <a href="{% roundurl 'draw-details' %}" class="btn btn-outline-primary">
      {% trans "Draw Details" %}
    </a>
    {% if pref.teams_in_debate == 'bp' and round.prev and not round.is_break_round %}
      <a href="{% roundurl 'draw-position-balance' %}" class="btn btn-outline-primary">
        {% trans "Position Balance" %}
      </a>
    {% endif %}
  </div>
{% endblock %}

{% block page-subnav-actions %}
  <a href="{% roundurl 'draw-display' %}" class="btn btn-outline-success">
    {% trans "Display Draw" %}<i data-feather="chevron-right"></i>
  </a>
{% endblock %}

tabbycat/draw/templates/draw_confirm_regeneration.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block page-title %}
  {% trans "Confirm draw regeneration" %}
{% endblock %}

{% block page-subnav-sections %}
  <a class="btn btn-outline-primary " href="{% roundurl 'draw' %}">
    <i data-feather="chevron-left"></i>{% trans "Back to Draw" %}
  </a>
{% endblock %}

{% block head-title %}
  <span class="emoji">🔥</span>
  {% blocktrans trimmed with round=round.name %}Confirm Draw Deletion for {{ round }}{% endblocktrans %}
{% endblock %}

{% block page-alerts %}

  <div class="alert alert-warning">
    {% blocktrans trimmed with round=round.name %}
    Do you really want to regenerate the draw for {{ round }}? This will
    delete <strong>all the debates in the current draw</strong> —  including
    their ballots and adjudicator allocations — and cannot be undone.
    You probably don't want to do this if any results have been entered!
    {% endblocktrans %}
  </div>

  <form method="POST" action="{% roundurl 'draw-regenerate' %}">
    {% csrf_token %}
    <button class="btn btn-block btn-danger " type="submit">
      {% blocktrans trimmed with round=round.name %}
      Yes, I want to delete the current draw for {{ round }}
      {% endblocktrans %}
    </button>
  </form>

{% endblock %}

tabbycat/draw/templates/draw_display_assistant.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block head-title %}📺 {% trans "Display Draw" %}{% endblock %}
{% block page-title %}{% trans "Display Draw" %}{% endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <ul class="list-group">

      {% trans "(for the briefing room)" as briefing_room_subtext %}

      {% if tournament.current_rounds|length == 1 %}

        {% tournamenturl 'draw-assistant-display-current-rounds-by-venue' as url %}
        {% trans "Display Draw ordered by Room" as text %}
        {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="🏫" blank=True %}

        {% tournamenturl 'draw-assistant-display-current-rounds-by-team' as url %}
        {% trans "Display Draw ordered by Team" as text %}
        {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="👭" blank=True %}

      {% else %}

        {% tournamenturl 'draw-assistant-display-current-rounds-by-venue' as url %}
        {% trans "Display Draws for <strong>All Current Rounds</strong> ordered by Room" as text %}
        {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="🏫" blank=True %}

        {% tournamenturl 'draw-assistant-display-current-rounds-by-team' as url %}
        {% trans "Display Draws for <strong>All Current Rounds</strong> ordered by Team" as text %}
        {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="👭" blank=True %}

        {% for round in tournament.current_rounds %}

          {% roundurl 'draw-assistant-display-specific-round-by-venue' round as url %}
          {% blocktrans trimmed with round=round.name asvar text %}
            Display Draw for <strong>{{ round }}</strong> ordered by Room
          {% endblocktrans %}
          {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="🏫" blank=True %}

          {% roundurl 'draw-assistant-display-specific-round-by-team' round as url %}
          {% blocktrans trimmed with round=round.name asvar text %}
            Display Draw for <strong>{{ round }}</strong> ordered by Team
          {% endblocktrans %}
          {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="👭" blank=True %}

        {% endfor %}

      {% endif %}

      {% if pref.assistant_access == "all_areas" %}
        {% tournamenturl 'motions-assistant-display' as url %}
        {% trans "Display Motions" as text %}
        {% include "components/item-action.html" with subtext=briefing_room_subtext emoji="📃" blank=True %}
      {% endif %}

    </ul>
    <ul class="list-group mt-3">

      {% trans "(for printing)" as printing_subtext %}

      {% if pref.assistant_access == "all_areas" %}
        {% tournamenturl 'printing-assistant-scoresheets' as url %}
        {% trans "View Ballot Forms" as text %}
        {% include "components/item-action.html" with subtext=printing_subtext emoji="💯" %}
      {% endif %}

      {% tournamenturl 'printing-assistant-feedback' as url %}
      {% trans "View Feedback Forms" as text %}
      {% include "components/item-action.html" with subtext=printing_subtext emoji="🙅" %}

    </ul>
  </div>
</div>

{% endblock content %}

tabbycat/draw/templates/draw_not_released.html
{% extends "base.html" %}
{% load i18n %}

{% block page-alerts %}

  {% if round %}
    {% blocktrans trimmed with round=round.name asvar message %}
      The draw for {{ round }} has yet to be released.
    {% endblocktrans %}
  {% else %}
    {% trans "The draw for the next round has yet to be released." as message %}
  {% endif %}
  {% include "components/alert.html" with type="info" icon="alert-circle" %}

{% endblock %}

tabbycat/draw/templates/draw_status_draft.html
{% extends "tables/base_vue_table.html" %}
{% load debate_tags i18n standingsformat %}

{% block page-subnav-sections %}
  <a href="{% roundurl 'draw-confirm-regenerate' %}" class="btn btn-outline-danger">
    <i data-feather="chevron-left"></i> {% trans "Delete Draw" %}
  </a>
  <a href="{% roundurl 'edit-debate-teams' round %}" class="btn btn-outline-primary">
    {% trans "Edit Sides/Matchups" %}
  </a>
{% endblock %}

{% block page-subnav-actions %}
  <form id="confirmForm" method="POST" action="{% roundurl 'draw-confirm' %}">
    {% csrf_token %}
    <button id="confirmDraw" class="btn btn-success" type="submit">
      {% trans "Confirm Draw" %}<i data-feather="chevron-right"></i>
    </button>
  </form>
{% endblock %}

{% block page-alerts %}
  {% if pref.team_standings_precedence|length == 0 %}
    {% tournamenturl 'options-tournament-section' section='standings' as standings_config_url %}
    {% blocktrans trimmed asvar message %}
      The team standings precedence is empty. This means that teams aren't
      ranked according to any metrics, so all teams are in a single bracket
      containing everyone. If this isn't what you intended, set the team
      standings precedence in the
      <a href="{{ standings_config_url }}" class="alert-link">Standings section
      of this tournament's configuration</a>,
      then delete and recreate the draw. In most
      tournaments, the first metric should be points or wins.
    {% endblocktrans %}
    {# Now just 'info' because the user already clicked through the 'warning' when creating the draw. #}
    {% include "components/alert.html" with type="info" icon="alert-circle" %}
  {% endif %}

  {% if pref.teams_in_debate == 'bp' and pref.team_standings_precedence|length > 0 and pref.team_standings_precedence.0 != 'points' %}
    {% tournamenturl 'options-tournament-section' section='standings' as standings_config_url %}
    {% blocktrans trimmed asvar message with metric=pref.team_standings_precedence.0|teammetricname %}
      Brackets are formed using the first metric in the team standings precedence, which is currently
      set to <strong>{{ metric }}</strong>, rather than team points, which is the more usual convention.
      If this isn't what you wanted, you can
      <a href="{{ standings_config_url }}" class="alert-link">change the team standings precedence
      in the standings configuration page</a>.
    {% endblocktrans %}
    {% include "components/alert.html" with type="info" icon='alert-circle' %}
  {% endif %}

  {% if round.draw_type == round.DRAW_MANUAL and round.debate_set.count == 0 %}
    {% roundurl 'edit-debate-teams' round as edit_matchups_url %}
    {% blocktrans trimmed asvar message %}
      The draw type for this round is set to <strong>manual</strong>, so Tabbycat has just made a
      blank draw. Head on over to
      <a href="{{ edit_matchups_url }}" class="alert-link">Edit Sides/Matchups</a>
      to fill it in.
    {% endblocktrans %}
    {% include "components/alert.html" with type="info" icon='alert-circle' %}
  {% endif %}

  {% if pref.adj_min_score == pref.adj_max_score %}
    {% tournamenturl 'options-tournament-section' section='feedback' as feedback_config_url %}
    {% blocktrans trimmed asvar message %}
      The adjudicator score range is 0, and so adjudicator scores will be ignored when allocating. You can <a href="{{ feedback_config_url }}" class="alert-link">change the adjudicator score range in the feedback configuration page</a>.
    {% endblocktrans %}
    {% include "components/alert.html" with type="info" icon='alert-circle' %}
  {% endif %}
{% endblock %}

{% block content %}

  {% if round.is_break_round %}
    {% blocktrans trimmed asvar p1 %}
      Tabbycat assigns sides in elimination rounds randomly. However, because in elimination rounds, many tournaments draw lots for sides in front of an audience, the sides are marked as "unconfirmed", so that it doesn't look like sides have been pre-assigned. After you confirm the draw, you'll need to confirm sides on the "Edit Sides/Matchups" page, even if you wish to accept Tabbycat's random assignment.
    {% endblocktrans %}
    {% include "components/explainer-card.html" with type="warning" %}
  {% endif %}

  {% if round.draw_status == 'D' and round.prev and not round.is_break_round and pref.teams_in_debate == 'bp' and highlighted_cells_exist %}
      {% blocktrans trimmed asvar p1 %}
        Highlighted cells relate to changes in position balance, as follows:
        <ul>
          <li>Red cells indicates that the team could not be allocated a position that maintains
          position balance.</li>
          <li>Yellow cells indicate that the team was previously imbalanced, and is given the best position
           possible in this draw, but is nonetheless still imbalanced.</li>
          <li>Green cells indicate that the team's previous imbalance is resolved with this draw.</li>
        </ul>
      {% endblocktrans %}
      {% include "components/explainer-card.html" with type="info" %}
  {% endif %}

  {{ block.super }}
{% endblock %}

tabbycat/draw/templates/draw_status_none.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block page-alerts %}
  {% roundurl 'availability-index' as availability_url %}
  {% blocktrans trimmed asvar message with round=round.name %}
    A draw for {{ round }} hasn't yet been generated. To generate one, go
    to the <a href="{{ availability_url }}" class="alert-link">Availability section</a>.
  {% endblocktrans %}
  {% include 'components/alert.html' with type="warning" %}
{% endblock %}

tabbycat/draw/templates/draw_subpage.html
{% extends "draw_base.html" %}
{% load debate_tags i18n %}

{% block page-subnav-sections %}
  <a class="btn btn-outline-primary " href="{% roundurl 'draw' %}">
    <i data-feather="chevron-left"></i>{% trans "Back to Draw" %}
  </a>
{% endblock %}

tabbycat/draw/templates/edit_debate_teams.html
{% extends "base_drag_and_drop.html" %}

{% block component %}
  <edit-debate-teams-container :initial-data="allData"></edit-debate-teams-container>
{% endblock component %}

tabbycat/draw/templates/position_balance_break.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block page-alerts %}
  {% roundurl 'availability-index' as checkins_url %}
  {% trans "Position balance reports aren't computed for elimination rounds." as message %}
  {% include 'components/alert.html' with type="info" %}
{% endblock %}

tabbycat/draw/templates/position_balance_nonbp.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block page-alerts %}
  {% roundurl 'availability-index' as checkins_url %}
  {% trans "Position balance reports are only available for British Parliamentary tournaments." as message %}
  {% include 'components/alert.html' with type="info" %}
{% endblock %}

tabbycat/draw/templates/position_balance_round1.html
{% extends "base.html" %}
{% load debate_tags i18n %}

{% block page-alerts %}
  {% roundurl 'availability-index' as checkins_url %}
  {% trans "Position balance reports aren't computed for the first round of a tournament." as message %}
  {% include 'components/alert.html' with type="info" %}
{% endblock %}